"""add road health segments and status history

Revision ID: edd5ed491120
Revises: 
Create Date: 2026-08-26 13:05:38.123396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd5ed491120'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('road_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.String(length=50), nullable=False),
    sa.Column('road_name', sa.String(length=255), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('length_km', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_road_segments_id'), 'road_segments', ['id'], unique=False)
    op.create_index(op.f('ix_road_segments_segment_id'), 'road_segments', ['segment_id'], unique=True)
    op.create_table('defect_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defect_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defect_status_history_defect_id'), 'defect_status_history', ['defect_id'], unique=False)
    op.create_index(op.f('ix_defect_status_history_id'), 'defect_status_history', ['id'], unique=False)
    op.add_column('defects', sa.Column('road_segment_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_defects_road_segment_id'), 'defects', ['road_segment_id'], unique=False)
    op.create_foreign_key(None, 'defects', 'road_segments', ['road_segment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'defects', type_='foreignkey')
    op.drop_index(op.f('ix_defects_road_segment_id'), table_name='defects')
    op.drop_column('defects', 'road_segment_id')
    op.drop_index(op.f('ix_defect_status_history_id'), table_name='defect_status_history')
    op.drop_index(op.f('ix_defect_status_history_defect_id'), table_name='defect_status_history')
    op.drop_table('defect_status_history')
    op.drop_index(op.f('ix_road_segments_segment_id'), table_name='road_segments')
    op.drop_index(op.f('ix_road_segments_id'), table_name='road_segments')
    op.drop_table('road_segments')
    # ### end Alembic commands ###
